[workspace]
authors = ["mattia s. <mttsgro@gmail.com>"]
channels = ["conda-forge"]
name = "PlasBin-HMF_comparison-slurm"
platforms = ["osx-arm64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
zensical = ">=0.0.27"
pygments = ">=2.19.2"

[pypi-dependencies]
markdown-gfm-admonition = ">=0.3.0"
